### ISSUE TITLE
AuthController error

### ISSUE THREAD

**Issue by vogljd** [vishwac09/authzero#6]
I installed and enabled the authzero module on a Drupal 9 site but when I go to the user/login page I get this error:

TypeError: Argument 1 passed to Drupal\auth0\Controller\AuthController::__construct() must be an instance of Drupal\user\PrivateTempStoreFactory, instance of Drupal\Core\TempStore\PrivateTempStoreFactory given, called in /code/web/modules/auth0/src/Controller/AuthController.php on line 234 in Drupal\auth0\Controller\AuthController->__construct() (line 189 of modules/auth0/src/Controller/AuthController.php).

Drupal\auth0\Controller\AuthController->__construct(Object, Object, Object, Object, Object, Object, Object, Object) (Line: 234)
Drupal\auth0\Controller\AuthController::create(Object) (Line: 28)
Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition('\Drupal\auth0\Controller\AuthController') (Line: 117)
Drupal\Core\Controller\ControllerResolver->createController('\Drupal\auth0\Controller\AuthController::login') (Line: 69)
Drupal\Core\Controller\ControllerResolver->getControllerFromDefinition('\Drupal\auth0\Controller\AuthController::login', '/user/login') (Line: 85)
Drupal\Core\Controller\ControllerResolver->getController(Object) (Line: 141)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 191)
Drupal\page_cache\StackMiddleware\PageCache->fetch(Object, 1, 1) (Line: 128)
Drupal\page_cache\StackMiddleware\PageCache->lookup(Object, 1, 1) (Line: 82)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 50)
Drupal\ban\BanMiddleware->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

Please advise. Thank you.

**Comment by vogljd** [comment]
I had the d8 auth0 module installed but not enabled. I uninstalled it and the error message went away, although I'm just seeing the generic login page.

**Comment by vishwac09** [comment]
@vogljd on installing the authzero module, open the **/auth0/login** url to get redirected to Auth0 Login page, have not altered the /user/login route. If needed we can think of adding a option in the config form, which overrides the default route.

**Comment by vishwac09** [comment]
@vogljd is your issue resolved ?

**Comment by vishwac09** [comment]
@vogljd you want to have Drupal site theme header/footer on your Auth0 login page ? Go to Universal Login page inside auth0 to theme it, youc an add custom CSS/JS on it. Check this link for more details https://auth0.com/docs/customize/universal-login-pages or do connect with Auth0 Team for more info.

**Comment by vogljd** [comment]
Thanks, I'll check it out.

--------
Jim Vogl, *Web Applications Developer*
Larimer County
200 W. Oak St., Fort Collins CO. 80521

*970-498-5048 (phone)*970-498-5099 (fax)
***@***.***

**Comment by vishwac09** [comment]
Need to update README.md file to add more details on the working of module

**Comment by vogljd** [comment]
Drupal 7 used the auth0_user table, This module doesn't use a database
lookup table for its users?

**Comment by vishwac09** [comment]
Check file AuthZeroController.php function auth0Callback, line 71 user_load_by_mail($user['email']) will look for the email provided by the auth0 library into drupal database in the users table. There is no need to maintain a separate table for this functionality.
